### ISSUE TITLE
hello ! The sileo bootstrap not work on IOS14.2

### ISSUE THREAD

**Issue by wnctrunk** [coolstar/Odyssey-bootstrap#15] opened 2020-11-11 05:12 UTC
Sileo is working ,but plug-in does not works

**Comment by raspberryenvoie** [comment] 2020-11-11 09:50
Can confirm libhooker doesn't work on iOS 14.2 so tweaks are not injected but Sileo works fine

**Comment by wnctrunk** [comment] 2020-11-14 08:46
> Can confirm libhooker doesn't work on iOS 14.2 so tweaks are not injected but Sileo works fine

If you start libhooker for terminal ,it works.but its not start with system. It seems that /etc/rc.d is not working

**Comment by raspberryenvoie** [comment] 2020-11-14 10:29
How do I start it from terminal?

**Comment by Yaya48** [comment] 2020-11-14 12:53
> How do I start it from terminal?

sudo /etc/rc.d/libhooker && sudo ldrestart

**Comment by raspberryenvoie** [comment] 2020-11-14 13:36
> > How do I start it from terminal?
> 
> sudo /etc/rc.d/libhooker && sudo ldrestart

Thanks, that worked :)

**Comment by Yaya48** [comment] 2020-11-14 15:26
> > > How do I start it from terminal?
> > 
> > 
> > sudo /etc/rc.d/libhooker && sudo ldrestart
> 
> Thanks, that worked :)

np

**Comment by m1stadev** [comment] 2021-05-07 19:02
This has been fixed with a recent libhooker update.

**Closed by m1stadev** 2021-05-07 19:02 UTC

**Comment by raspberryenvoie** [comment] 2021-05-07 19:24
Just to let you know, this issue was caused by checkra1n not odysseyra1n.
It was fixed in version 0.12.1. From checkra.in:
> Fixes an issue that would often cause Safe Mode to be entered on iOS 14.2 regardless of whether the user requested it or not
